# General quarkus configuration
quarkus:
  
  application:
    name: ${APPLICATION_NAME:coinbase-etl}

  profile: ${APPLICATION_PROFILE:prod}

  http:
    host: ${APPLICATION_HOST:0.0.0.0}
    port: ${APPLICATION_PORT:8080}

  log:
    level: INFO

  thread-pool:
    core-threads: 1
    max-threads: 1
    prefill: true

  smallrye-metrics:
    path: /metrics
    micrometer:
      compatibility: true

  vertx:
    worker-pool-size: 2
    internal-blocking-pool-size: 2

# Coinbase configuration
coinbase:
  # URI to the Coinbase websocket feed
  websocket: ${COINBASE_WSS_URI:wss://ws-feed.pro.coinbase.com}
  # URI to the Coinbase Pro API
  api: ${COINBASE_API_URI:https://api.pro.coinbase.com}
  # Products to support
  product: ${COINBASE_PRODUCT:BTC-USD}
  # REST Client config.

# Coinbase REST client config.
coinbase-rest-client/mp-rest/url: ${coinbase.api}

# Kafka configuration
confluent:
  enabled: ${KAFKA_ENABLED:false}
  # Fetch Kafka config. from a property file using an absolute path (first)
  file: ${KAFKA_CONFIG_PATH}
  # Fetch Kafka config. from a property file located in resources (second)
  # Not recommended when using native build (resource must be added during build)
  resource: ${KAFKA_CONFIG_RESOURCE}
  # The topic to use to publish match events
  match: ${KAFKA_TOPICS_MATCHES}
  # The topic to use to publish tick events
  ticker: ${KAFKA_TOPICS_TICKERS}

# DEV profile - Suitable to local run without external dependencies
"%dev" :
  quarkus:
    log:
      category:
        "CoinbaseWSClientEndpoint":
          level: TRACE
        "MatchProducer":
          level: TRACE
        "TickerProducer":
          level: TRACE
        "MatchSyncer":
          level: TRACE

  coinbase:
    api: https://api-public.sandbox.pro.coinbase.com
    uri: wss://ws-feed-public.sandbox.pro.coinbase.com
    product: BTC-USD

  confluent:
    enabled: false

# Local run - with external dependencies
"%local":
  quarkus:
    log:
      category:
        "CoinbaseWSClientEndpoint":
          level: TRACE
        "MatchProducer":
          level: TRACE
        "TickerProducer":
          level: TRACE
        "MatchSyncer":
          level: TRACE
  coinbase:
    api: https://api-public.sandbox.pro.coinbase.com
    uri: wss://ws-feed-public.sandbox.pro.coinbase.com
    product: BTC-USD
  confluent:
    enabled: true
    resource: /kafka/kafka.properties
    match: coinbase-btc-usd-matches
    ticker: coinbase-btc-usd-tickers

# Test profile
"%test" :
  quarkus:
    log:
      category:
        "CoinbaseWSClientEndpoint":
          level: TRACE
        "MatchProducer":
          level: TRACE
        "TickerProducer":
          level: TRACE
        "MatchSyncer":
          level: TRACE

  coinbase:
    api: https://api-public.sandbox.pro.coinbase.com
    uri: wss://ws-feed-public.sandbox.pro.coinbase.com
    product: BTC-USD

  confluent:
    enabled: false
